### ISSUE TITLE
idea2022.1 插件无法安装

### ISSUE THREAD

**Issue by lianlianyi** [alibaba/compileflow-idea-designer#22]
![图片](https://user-images.githubusercontent.com/1701810/168723218-9cff11c5-794e-4613-99d4-80b65a7447ae.png)
![图片](https://user-images.githubusercontent.com/1701810/168723272-e8b1ae85-fcf1-48de-82e3-fe69e640e33d.png)

**Comment by xuan698400** [comment]
最新版本已经支持安装

**Comment by xuan698400** [comment]
看最新版本
