### ISSUE TITLE
这几个lib开源吗

### ISSUE THREAD

**Issue by SoftwareKing** [alibaba/compileflow-idea-designer#3]
* miglayout-core-5.3-SNAPSHOT.jar

* miglayout-swing-5.3-SNAPSHOT.jar

* rsyntaxtextarea-3.0.0-SNAPSHOT.jar

* mxgraph-all.jar

**Comment by voff12** [comment]
这个本身就是开源的。例如：https://github.com/mikaelgrev/miglayout
