### ISSUE TITLE
希望后续可以兼容黑色主题

### ISSUE THREAD

**Issue by tuzhis** [alibaba/compileflow-idea-designer#4]
在黑色背景（如darcula)下flow配色看不清，希望后续可以适配兼容

**Comment by voff12** [comment]
能否截一个图出来？

**Comment by tuzhis** [comment]
@voff12  超出框的部分看不清，不过突然发现框可以拖动修改大小，应该还好了

![image](https://user-images.githubusercontent.com/8074454/97251870-af6d8d80-1843-11eb-8420-b1bffefafa7c.png)

**Comment by xuan698400** [comment]
最新版本已支持主题的切换。可以调整经典模式或者彩色模式。
