### ISSUE TITLE
中仓库地址外网无法使用

### ISSUE THREAD

**Issue by wangchaomail** [alibaba/compileflow-idea-designer#5]
build.gradle 文件中，仓库地址使用的是一个阿里巴巴内网的仓库地址，外网无法正常使用
http://mvnrepo.alibaba-inc.com/nexus/content/groups/public/

**Comment by xuan698400** [comment]
> build.gradle 文件中，仓库地址使用的是一个阿里巴巴内网的仓库地址，外网无法正常使用
> http://mvnrepo.alibaba-inc.com/nexus/content/groups/public/

集团内部仓库依赖已去掉，设计器内部依赖的所有jar，都在libs下。
