### ISSUE TITLE
循环节点控制没有中断机制

### ISSUE THREAD

**Issue by wangchaomail** [alibaba/compileflow-idea-designer#7]
循环节点中，有很多个节点，这时候有break 和continue 的机制就好了。现在遇到了一些问题，需要有break，和continue来体检结束流程。

**Comment by xuan698400** [comment]
> 循环节点中，有很多个节点，这时候有break 和continue 的机制就好了。现在遇到了一些问题，需要有break，和continue来体检结束流程。

目前是有这种场景是吧  其实引擎是支持的 ，只是设计器暂时没有支持，我找时间支持下。

**Comment by xuan698400** [comment]
> 循环节点中，有很多个节点，这时候有break 和continue 的机制就好了。现在遇到了一些问题，需要有break，和continue来体检结束流程。

已支持循环节点的conitnue节点和break节点。版本：1.0.6
